spring:
  security:
    user:
      password: 1
#  redis:
#    host: localhost
#    port: 6379
  datasource:
    url: jdbc:mariadb://gpuidblab.kro.kr:3306/todaysmenudb
    username: idblab
    password: idblab1145
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug